### ISSUE TITLE
Merge into brs-emu

### ISSUE THREAD

**Issue by upintheairsheep** [lvcabral/brs-emu-app#117]
It would be more convenient for brs-emu-app to be merged into brs-emu just so it's just cleaner overall.

**Comment by lvcabral** [comment]
I will not integrate, and I can explain why. There are at least two more projects/repositories I will release soon that also uses the `brs-emu` library, I'm actually even considering remove the `web` app to its own repository, and leave there only a simple example. The `brs-emu` is going to be a better `npm` package in the next release.

It makes easier to maintain then whole build and packaging, and give freedom to have independent releases, I've been releasing it together because it was the alpha and beta stages, but in the future I want each project to have its own timeline of releases.

**Comment by upintheairsheep** [comment]
I just found out that this is legitimately just a wrapper for brs-emu.
